/*
Copyright (c) 2011 Andrew Wilkins <axwalk@gmail.com>

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

/* Define this to ensure only the limited API is used, so we can ensure forward
 * binary compatibility. */
#define Py_LIMITED_API

#include <Python.h>

#include <iostream>
#include "preprocessor.hpp"
#include "token_iterator.hpp"
#include "token.hpp"

static PyModuleDef preprocessormodule = {
    PyModuleDef_HEAD_INIT,
    "_preprocessor",
    "Extension module to expose a native C++ preprocessor.",
    -1,
    NULL, NULL, NULL, NULL, NULL
};

extern "C" {
PyMODINIT_FUNC
PyInit__preprocessor(void)
{
    PyObject *PreprocessorType = csnake::python::init_preprocessor_type();
    if (!PreprocessorType)
        return NULL;
    if (!csnake::python::init_token_iterator_type())
        return NULL;
    PyObject *TokenType = (PyObject*)csnake::python::init_token_type();
    if (!TokenType)
        return NULL;

    // Initialise module.
    PyObject *module = PyModule_Create(&preprocessormodule);
    if (!module)
        return NULL;

    // Add types.
    Py_INCREF(PreprocessorType);
    Py_INCREF(TokenType);
    PyModule_AddObject(module, "Preprocessor", PreprocessorType);
    PyModule_AddObject(module, "Token", TokenType);

    // Add constants (token IDs). Unfortunately the categories can not be
    // determined programmatically, and the category is needed to get the
    // complete token ID.
#define ADD_TOKEN_CONSTANT(token) \
    PyModule_AddIntConstant(module, #token, boost::wave::token)

    ADD_TOKEN_CONSTANT(T_AND);
    ADD_TOKEN_CONSTANT(T_AND_ALT);
    ADD_TOKEN_CONSTANT(T_ANDAND);
    ADD_TOKEN_CONSTANT(T_ANDAND_ALT);
    ADD_TOKEN_CONSTANT(T_ASSIGN);
    ADD_TOKEN_CONSTANT(T_ANDASSIGN);
    ADD_TOKEN_CONSTANT(T_ANDASSIGN_ALT);
    ADD_TOKEN_CONSTANT(T_OR);
    ADD_TOKEN_CONSTANT(T_OR_ALT);
    ADD_TOKEN_CONSTANT(T_OR_TRIGRAPH);
    ADD_TOKEN_CONSTANT(T_ORASSIGN);
    ADD_TOKEN_CONSTANT(T_ORASSIGN_ALT);
    ADD_TOKEN_CONSTANT(T_ORASSIGN_TRIGRAPH);
    ADD_TOKEN_CONSTANT(T_XOR);
    ADD_TOKEN_CONSTANT(T_XOR_ALT);
    ADD_TOKEN_CONSTANT(T_XOR_TRIGRAPH);
    ADD_TOKEN_CONSTANT(T_XORASSIGN);
    ADD_TOKEN_CONSTANT(T_XORASSIGN_ALT);
    ADD_TOKEN_CONSTANT(T_XORASSIGN_TRIGRAPH);
    ADD_TOKEN_CONSTANT(T_COMMA);
    ADD_TOKEN_CONSTANT(T_COLON);
    ADD_TOKEN_CONSTANT(T_DIVIDE);
    ADD_TOKEN_CONSTANT(T_DIVIDEASSIGN);
    ADD_TOKEN_CONSTANT(T_DOT);
    ADD_TOKEN_CONSTANT(T_DOTSTAR);
    ADD_TOKEN_CONSTANT(T_ELLIPSIS);
    ADD_TOKEN_CONSTANT(T_EQUAL);
    ADD_TOKEN_CONSTANT(T_GREATER);
    ADD_TOKEN_CONSTANT(T_GREATEREQUAL);
    ADD_TOKEN_CONSTANT(T_LEFTBRACE);
    ADD_TOKEN_CONSTANT(T_LEFTBRACE_ALT);
    ADD_TOKEN_CONSTANT(T_LEFTBRACE_TRIGRAPH);
    ADD_TOKEN_CONSTANT(T_LESS);
    ADD_TOKEN_CONSTANT(T_LESSEQUAL);
    ADD_TOKEN_CONSTANT(T_LEFTPAREN);
    ADD_TOKEN_CONSTANT(T_LEFTBRACKET);
    ADD_TOKEN_CONSTANT(T_LEFTBRACKET_ALT);
    ADD_TOKEN_CONSTANT(T_LEFTBRACKET_TRIGRAPH);
    ADD_TOKEN_CONSTANT(T_MINUS);
    ADD_TOKEN_CONSTANT(T_MINUSASSIGN);
    ADD_TOKEN_CONSTANT(T_MINUSMINUS);
    ADD_TOKEN_CONSTANT(T_PERCENT);
    ADD_TOKEN_CONSTANT(T_PERCENTASSIGN);
    ADD_TOKEN_CONSTANT(T_NOT);
    ADD_TOKEN_CONSTANT(T_NOT_ALT);
    ADD_TOKEN_CONSTANT(T_NOTEQUAL);
    ADD_TOKEN_CONSTANT(T_NOTEQUAL_ALT);
    ADD_TOKEN_CONSTANT(T_OROR);
    ADD_TOKEN_CONSTANT(T_OROR_ALT);
    ADD_TOKEN_CONSTANT(T_OROR_TRIGRAPH);
    ADD_TOKEN_CONSTANT(T_PLUS);
    ADD_TOKEN_CONSTANT(T_PLUSASSIGN);
    ADD_TOKEN_CONSTANT(T_PLUSPLUS);
    ADD_TOKEN_CONSTANT(T_ARROW);
    ADD_TOKEN_CONSTANT(T_ARROWSTAR);
    ADD_TOKEN_CONSTANT(T_QUESTION_MARK);
    ADD_TOKEN_CONSTANT(T_RIGHTBRACE);
    ADD_TOKEN_CONSTANT(T_RIGHTBRACE_ALT);
    ADD_TOKEN_CONSTANT(T_RIGHTBRACE_TRIGRAPH);
    ADD_TOKEN_CONSTANT(T_RIGHTPAREN);
    ADD_TOKEN_CONSTANT(T_RIGHTBRACKET);
    ADD_TOKEN_CONSTANT(T_RIGHTBRACKET_ALT);
    ADD_TOKEN_CONSTANT(T_RIGHTBRACKET_TRIGRAPH);
    ADD_TOKEN_CONSTANT(T_COLON_COLON);
    ADD_TOKEN_CONSTANT(T_SEMICOLON);
    ADD_TOKEN_CONSTANT(T_SHIFTLEFT);
    ADD_TOKEN_CONSTANT(T_SHIFTLEFTASSIGN);
    ADD_TOKEN_CONSTANT(T_SHIFTRIGHT);
    ADD_TOKEN_CONSTANT(T_SHIFTRIGHTASSIGN);
    ADD_TOKEN_CONSTANT(T_STAR);
    ADD_TOKEN_CONSTANT(T_COMPL);
    ADD_TOKEN_CONSTANT(T_COMPL_ALT);
    ADD_TOKEN_CONSTANT(T_COMPL_TRIGRAPH);
    ADD_TOKEN_CONSTANT(T_STARASSIGN);
    ADD_TOKEN_CONSTANT(T_ASM);
    ADD_TOKEN_CONSTANT(T_AUTO);
    ADD_TOKEN_CONSTANT(T_BOOL);
    ADD_TOKEN_CONSTANT(T_FALSE);
    ADD_TOKEN_CONSTANT(T_TRUE);
    ADD_TOKEN_CONSTANT(T_BREAK);
    ADD_TOKEN_CONSTANT(T_CASE);
    ADD_TOKEN_CONSTANT(T_CATCH);
    ADD_TOKEN_CONSTANT(T_CHAR);
    ADD_TOKEN_CONSTANT(T_CLASS);
    ADD_TOKEN_CONSTANT(T_CONST);
    ADD_TOKEN_CONSTANT(T_CONSTCAST);
    ADD_TOKEN_CONSTANT(T_CONTINUE);
    ADD_TOKEN_CONSTANT(T_DEFAULT);
    ADD_TOKEN_CONSTANT(T_DELETE);
    ADD_TOKEN_CONSTANT(T_DO);
    ADD_TOKEN_CONSTANT(T_DOUBLE);
    ADD_TOKEN_CONSTANT(T_DYNAMICCAST);
    ADD_TOKEN_CONSTANT(T_ELSE);
    ADD_TOKEN_CONSTANT(T_ENUM);
    ADD_TOKEN_CONSTANT(T_EXPLICIT);
    ADD_TOKEN_CONSTANT(T_EXPORT);
    ADD_TOKEN_CONSTANT(T_EXTERN);
    ADD_TOKEN_CONSTANT(T_FLOAT);
    ADD_TOKEN_CONSTANT(T_FOR);
    ADD_TOKEN_CONSTANT(T_FRIEND);
    ADD_TOKEN_CONSTANT(T_GOTO);
    ADD_TOKEN_CONSTANT(T_IF);
    ADD_TOKEN_CONSTANT(T_INLINE);
    ADD_TOKEN_CONSTANT(T_INT);
    ADD_TOKEN_CONSTANT(T_LONG);
    ADD_TOKEN_CONSTANT(T_MUTABLE);
    ADD_TOKEN_CONSTANT(T_NAMESPACE);
    ADD_TOKEN_CONSTANT(T_NEW);
    ADD_TOKEN_CONSTANT(T_OPERATOR);
    ADD_TOKEN_CONSTANT(T_PRIVATE);
    ADD_TOKEN_CONSTANT(T_PROTECTED);
    ADD_TOKEN_CONSTANT(T_PUBLIC);
    ADD_TOKEN_CONSTANT(T_REGISTER);
    ADD_TOKEN_CONSTANT(T_REINTERPRETCAST);
    ADD_TOKEN_CONSTANT(T_RETURN);
    ADD_TOKEN_CONSTANT(T_SHORT);
    ADD_TOKEN_CONSTANT(T_SIGNED);
    ADD_TOKEN_CONSTANT(T_SIZEOF);
    ADD_TOKEN_CONSTANT(T_STATIC);
    ADD_TOKEN_CONSTANT(T_STATICCAST);
    ADD_TOKEN_CONSTANT(T_STRUCT);
    ADD_TOKEN_CONSTANT(T_SWITCH);
    ADD_TOKEN_CONSTANT(T_TEMPLATE);
    ADD_TOKEN_CONSTANT(T_THIS);
    ADD_TOKEN_CONSTANT(T_THROW);
    ADD_TOKEN_CONSTANT(T_TRY);
    ADD_TOKEN_CONSTANT(T_TYPEDEF);
    ADD_TOKEN_CONSTANT(T_TYPEID);
    ADD_TOKEN_CONSTANT(T_TYPENAME);
    ADD_TOKEN_CONSTANT(T_UNION);
    ADD_TOKEN_CONSTANT(T_UNSIGNED);
    ADD_TOKEN_CONSTANT(T_USING);
    ADD_TOKEN_CONSTANT(T_VIRTUAL);
    ADD_TOKEN_CONSTANT(T_VOID);
    ADD_TOKEN_CONSTANT(T_VOLATILE);
    ADD_TOKEN_CONSTANT(T_WCHART);
    ADD_TOKEN_CONSTANT(T_WHILE);
    ADD_TOKEN_CONSTANT(T_PP_DEFINE);
    ADD_TOKEN_CONSTANT(T_PP_IF);
    ADD_TOKEN_CONSTANT(T_PP_IFDEF);
    ADD_TOKEN_CONSTANT(T_PP_IFNDEF);
    ADD_TOKEN_CONSTANT(T_PP_ELSE);
    ADD_TOKEN_CONSTANT(T_PP_ELIF);
    ADD_TOKEN_CONSTANT(T_PP_ENDIF);
    ADD_TOKEN_CONSTANT(T_PP_ERROR);
    ADD_TOKEN_CONSTANT(T_PP_LINE);
    ADD_TOKEN_CONSTANT(T_PP_PRAGMA);
    ADD_TOKEN_CONSTANT(T_PP_UNDEF);
    ADD_TOKEN_CONSTANT(T_PP_WARNING);
    ADD_TOKEN_CONSTANT(T_IDENTIFIER);
    ADD_TOKEN_CONSTANT(T_OCTALINT);
    ADD_TOKEN_CONSTANT(T_DECIMALINT);
    ADD_TOKEN_CONSTANT(T_HEXAINT);
    ADD_TOKEN_CONSTANT(T_INTLIT);
    ADD_TOKEN_CONSTANT(T_LONGINTLIT);
    ADD_TOKEN_CONSTANT(T_FLOATLIT);
    ADD_TOKEN_CONSTANT(T_FIXEDPOINTLIT);
    ADD_TOKEN_CONSTANT(T_CCOMMENT);
    ADD_TOKEN_CONSTANT(T_CPPCOMMENT);
    ADD_TOKEN_CONSTANT(T_CHARLIT);
    ADD_TOKEN_CONSTANT(T_STRINGLIT);
    ADD_TOKEN_CONSTANT(T_CONTLINE);
    ADD_TOKEN_CONSTANT(T_SPACE);
    ADD_TOKEN_CONSTANT(T_SPACE2);
    ADD_TOKEN_CONSTANT(T_NEWLINE);
    ADD_TOKEN_CONSTANT(T_GENERATEDNEWLINE);
    ADD_TOKEN_CONSTANT(T_POUND_POUND);
    ADD_TOKEN_CONSTANT(T_POUND_POUND_ALT);
    ADD_TOKEN_CONSTANT(T_POUND_POUND_TRIGRAPH);
    ADD_TOKEN_CONSTANT(T_POUND);
    ADD_TOKEN_CONSTANT(T_POUND_ALT);
    ADD_TOKEN_CONSTANT(T_POUND_TRIGRAPH);
    ADD_TOKEN_CONSTANT(T_ANY);
    ADD_TOKEN_CONSTANT(T_ANY_TRIGRAPH);
    ADD_TOKEN_CONSTANT(T_PP_INCLUDE);
    ADD_TOKEN_CONSTANT(T_PP_QHEADER);
    ADD_TOKEN_CONSTANT(T_PP_HHEADER);
    ADD_TOKEN_CONSTANT(T_PP_INCLUDE_NEXT);
    ADD_TOKEN_CONSTANT(T_PP_QHEADER_NEXT);
    ADD_TOKEN_CONSTANT(T_PP_HHEADER_NEXT);
    ADD_TOKEN_CONSTANT(T_EOF);
    ADD_TOKEN_CONSTANT(T_EOI);
    ADD_TOKEN_CONSTANT(T_PP_NUMBER);
    ADD_TOKEN_CONSTANT(T_MSEXT_INT8);
    ADD_TOKEN_CONSTANT(T_MSEXT_INT16);
    ADD_TOKEN_CONSTANT(T_MSEXT_INT32);
    ADD_TOKEN_CONSTANT(T_MSEXT_INT64);
    ADD_TOKEN_CONSTANT(T_MSEXT_BASED);
    ADD_TOKEN_CONSTANT(T_MSEXT_DECLSPEC);
    ADD_TOKEN_CONSTANT(T_MSEXT_CDECL);
    ADD_TOKEN_CONSTANT(T_MSEXT_FASTCALL);
    ADD_TOKEN_CONSTANT(T_MSEXT_STDCALL);
    ADD_TOKEN_CONSTANT(T_MSEXT_TRY);
    ADD_TOKEN_CONSTANT(T_MSEXT_EXCEPT);
    ADD_TOKEN_CONSTANT(T_MSEXT_FINALLY);
    ADD_TOKEN_CONSTANT(T_MSEXT_LEAVE);
    ADD_TOKEN_CONSTANT(T_MSEXT_INLINE);
    ADD_TOKEN_CONSTANT(T_MSEXT_ASM);
    ADD_TOKEN_CONSTANT(T_MSEXT_PP_REGION);
    ADD_TOKEN_CONSTANT(T_MSEXT_PP_ENDREGION);
    ADD_TOKEN_CONSTANT(T_IMPORT);

    return module;
}
}

